configName: sam_l21_xpro
folderName: sam_l21_xpro
format_version: v1.0
frameworkPath: ..\..\..
processor: ATSAML21J18B
projectName: hid_basic_sam_l21_xpro
settings:
  PackageFilter: audio;bootloader;bootloader_apps_uart;bsp;core;core_apps_sam_d21_da1;core_apps_sam_d5x_e5x;core_apps_sam_e70_s70_v70_v71;core_apps_sam_l21;core_apps_sam_l22;crypto;cryptoauthlib;csp;csp_apps_sam_d11;csp_apps_sam_d21_da1;csp_apps_sam_d5x_e5x;csp_apps_sam_e70_s70_v70_v71;csp_apps_sam_l22;Devices;dev_packs;gfx;gfx_apps;gfx_apps_sam_d5x_e5x;gfx_apps_sam_e70_s70_v70_v71;gfx_aria;harmony-services;MPLAB-Harmony-Reference-Apps;net;net_apps_sam_e5x;net_apps_sam_e70_v71;quick_docs;smartenergy;touch;usb;usb_apps_device;usb_apps_host;wireless_apps_winc1500;wireless_wifi
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAML21_DFP\3.6.105\saml21b\atdf\ATSAML21J18B.atdf
